#code for github actions

name: CI / CD

on:
  push:
    branches:
      - master

jobs:
  build_dev_test:
    name: Build Frontend and Backend For Dev files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Frontend and Backend For Dev files
        run: |
          cd ..
          cd ..
          cd frontend
          docker build -t dev-frontend -f Dockerfile.dev .
          cd .. 
          cd backend
          docker build -t dev-backend -f Dockerfile.dev .

      - name: Run Frontend and Backend For Testing Dev files
        run: |
          docker run --rm dev-frontend
          docker run --rm dev-backend

  build_prod:
    name: Build Frontend Backend and Nginx For Prod files
    runs-on: ubuntu-latest
    needs: build_dev_test

    steps:
      - uses: actions/checkout@v2

      - name: Build Frontend and Backend For Prod files
        run: |
          docker build -t aoudaa/dkr-frontend:latest -f ./frontend
          docker build -t aoudaa/dkr-backend:latest -f ./backend
          docker build -t aoudaa/dkr-nginx:latest -f ./nginx

  deploy:
    name: Deploy Frontend Backend and Nginx For Prod files
    runs-on: ubuntu-latest
    needs: build_prod

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Frontend Backend and Nginx For Prod files

        run: |
          docker push aoudaa/dkr-frontend:latest
          docker push aoudaa/dkr-backend:latest
          docker push aoudaa/dkr-nginx:latest

      - name: ssh into vm and run the script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/aoudaa/docker
            sh deploy.sh
